CREATE TABLE Projects (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name varchar(255) NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP
)

INSERT into Projects (ID, Name) VALUES ("TestProject");


CREATE TABLE IPs {
    ID int NOT NULL AUTOINCREMENT PRIMARY KEY,
    IP
}