modules:
  - name: "NetworkExplorator"
    file_path: "modules/enumeration/network_exploration.go"
    attack_id: "enum01"
    dependsOn : ""

  - name: "SMBCoece"
    attack_id: "exploit01"
    dependsOn:
      - "enum01"